create database salesman
drop table salesman
create table salesman
(salesmanId int,salesmanName varchar(100),salesmanCity varchar(100),salesmanCommission float) 
insert into salesman values(5001,'James','Newyork',0.12)
insert into salesman values(5002,'nail','paris',0.13)
insert into salesman values(5005,'pit','london',0.14)
insert into salesman values(5006,'mc','paris',0.15)
insert into salesman values(5007,'paul','rome',0.16)
insert into salesman values(5001,'lauson','san jose',0.15)
select *from salesman
select salesmanName,salesmanCommission from salesman



drop table orders
create table orders(ordersno int,orderspurchamt float,ordessdate date,orderscustomerid int,orderssalesmanid int)
insert into orders values(70001,150.5,'2012-10-05',3005,5002)
insert into orders values(70009,140.5,'2012-10-05',3001,5005)
insert into orders values(70002,130.5,'2012-10-05',3002,5001)
insert into orders values(70004,120.5,'2012-10-05',3009,5003)
insert into orders values(70007,110.5,'2012-10-05',3005,5002)
insert into orders values(70005,160.5,'2012-10-05',3007,5001)
insert into orders values(70008,170.5,'2012-10-05',3005,5001)
insert into orders values(70010,180.5,'2012-10-05',3005,5006)
insert into orders values(70003,100.5,'2012-10-05',3005,5003)
insert into orders values(70012,150.5,'2012-10-05',3005,5002)
select*from orders



drop table customer
create table customer(customerid int,customername varchar(50),customercity varchar(50),customergrade int,customersalesmanid int)
insert into customer values(3001,'nick','newyork',100,501)
insert into customer values(3002,'nick','paris',200,502)
insert into customer values(3003,'nick','london',300,501)
insert into customer values(3004,'nick','italy',400,501)
insert into customer values(3005,'nick','london',500,501)
insert into customer values(3006,'nick','newyork',100,501)
select*from customer


--1.write a SQL query to calculate average purchase amount of all orders. Return average purchase amount. 
select avg (orderspurchamt) 
from orders;

--2.write a SQL query to count the number of unique salespeople. Return number of salespeople. 
select count(salesmanId ) 
from salesman

--3.Write a SQL query to count the number of customers. Return number of customers.
select count(*) 
from customer

--4.write a SQL query to find the maximum purchase amount
select max (orderspurchamt) 
from orders

--5.write a SQL query to find the highest grade of the customers for each of the city. Return city, maximum grade
SELECT customercity,MAX(customergrade)
FROM customer
GROUP BY customercity

--6.write a SQL query to find the highest purchase amount ordered by each customer. Return customer ID, maximum purchase amount
select orderscustomerid ,max(orderspurchamt) from orders group by orderscustomerid 


--7write a SQL query to count number of orders by the combination of each order date and salesperson. Return order date, salesperson id
select count(*), ordessdate,orderssalesmanid from orders group by ordessdate,orderssalesmanid 

--8.write a SQL query to count number of salespeople who belongs to a city. Return number of salespeople

select count(*),salesmanCity from salesman

--9.write a SQL query to count all the orders generated on '2012-08-17'. Return number of orders.
select count(*) from orders where ordessdate='2012-10-05'

--10.write a SQL query to find the maximum order (purchase) amount generated by each salesperson. Filter the rows for the salesperson ID is in the range 5003 and 5008 (Begin and end values are included.). Return salesperson id and maximum purchase amount
select max(orderspurchamt) from orders group by orderssalesmanid having orderssalesmanid between 5002 and 5006

--11.write a SQL query stat to display all the information of all salesman
    select*from salesman

--12.write a SQL query stat to display specific columns like name and commission for all the salesman
select salesmanName,salesmanCommission from salesman

--13.Write a query to display the columns in a specific order like order date, salesman id, order number and purchase amount from for all the orders
select ordessdate,orderssalesmanid,ordersno,orderspurchamt from orders

--14.write a SQL query to find the salespeople who lives in the City of 'Paris'. Return salesperson's name, city.
select customername,customercity from customer where customercity='paris'


--15.write a SQL query to find those customers whose grade is 200. Return customer_id, cust_name, city, grade, salesman_id
select customerid,customername,customercity ,customersalesmanid from customer where customergrade=200

--16.write a SQL query to find the orders, which are delivered by a salesperson of ID. 5001. Return ord_no, ord_date, purch_amt
select ordersno,ordessdate,orderspurchamt from orders where orderssalesmanid=5001

--17.write a SQL query to find the salesperson and customer who belongs to same city. Return Salesman, cust_name and city
select salesmanName  AS "Salesman",
customer.customername, customercity 
from salesman,customer 
where salesmanCity=customercity


